# coding: utf-8

from twitter_helper import Account


accounts = [
    # Afghanistan
    Account(name="", twitter_handler='ashrafghani',
            country_representing='AF', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='mfa_afghanistan',
            country_representing='AF', role='',
            is_personal=False, verified=True),
    Account(name="", twitter_handler='afghanmissionun',
            country_representing='AF', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='ARG_AFG',
            country_representing='AF', role='',
            is_personal=True, verified=True),

    # Argentina
    Account(name="Mauricio Macri", twitter_handler='mauriciomacri',
            country_representing='AR', role='President',
            is_personal=True, verified=True),
    Account(name="Jorge Faurie", twitter_handler='jorgefaurie',
            country_representing='AR', role='Minister of Foreign Affairs',
            is_personal=True, verified=True),
    Account(name="Argentina at the United Nations", twitter_handler='argentinaun',
            country_representing='AR', role='',
            is_personal=False, verified=True),

    # Australia
    Account(name="Scott Morrison", twitter_handler='ScottMorrisonMP',
            country_representing='AU', role='Prime Minister',
            is_personal=True, verified=True),
    Account(name="Marise Payne", twitter_handler='MarisePayne',
            country_representing='AU', role='Minister for Foreign Affairs',
            is_personal=True, verified=True),
    Account(name="Gillian Bird", twitter_handler='AustraliaUN',
            country_representing='AU', role='Ambassador and Permanent Representative to the United Nations',
            is_personal=True, verified=True),

    # Brazil
    Account(name="Michel Temer", twitter_handler='micheltemer',
            country_representing='BR', role='President',
            is_personal=True, verified=True),
    Account(name="Aloysio Nunes", twitter_handler='aloysio_nunes',
            country_representing='BR', role='Minister of Foreign Affairs',
            is_personal=True, verified=True),
    Account(name="Itamaraty Brazil", twitter_handler='Itamaraty_EN',
            country_representing='BR', role='',
            is_personal=False, verified=True),
    Account(name="Brazil Mission UN", twitter_handler='brazil_un_ny',
            country_representing='BR', role='',
            is_personal=False, verified=False),

    # Canada
    Account(name="", twitter_handler='JustinTrudeau',
            country_representing='CA', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='cafreeland',
            country_representing='CA', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='blanchardCanada',
            country_representing='CA', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='CanadianPM',
            country_representing='CA', role='',
            is_personal=False, verified=True),

    # China
    Account(name="Chinese Mission to UN", twitter_handler='chinamission2un',
            country_representing='CN', role='',
            is_personal=False, verified=True),

    # European Union
    Account(name="", twitter_handler='JunckerEU',
            country_representing='EU', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='FedericaMog',
            country_representing='EU', role='',
            is_personal=True, verified=True),
    Account(name="ValedeAlmeidaEU", twitter_handler='ValedeAlmeidaEU',
            country_representing='EU', role='Ambassador to the United Nations',
            is_personal=True, verified=True),
    Account(name="European External Action Service", twitter_handler='eu_eeas',
            country_representing='EU', role='',
            is_personal=False, verified=True),

    # France
    Account(name="Emmanuel Macron", twitter_handler='EmmanuelMacron',
            country_representing='FR', role='President',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='jy_ledrian',
            country_representing='FR', role='Minister of Europe and Foreign Affairs',
            is_personal=True, verified=True),
    Account(name="La France à l'ONU", twitter_handler='franceonu',
            country_representing='FR', role='',
            is_personal=False, verified=True),

    # Germany
    Account(name="", twitter_handler='angelamerkelcdu',
            country_representing='DE', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='heikomaas',
            country_representing='DE', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='germanyun',
            country_representing='DE', role='',
            is_personal=True, verified=True),

    # India
    Account(name="", twitter_handler='narendramodi',
            country_representing='IN', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='SushmaSwaraj',
            country_representing='IN', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='AkbaruddinIndia',
            country_representing='IN', role='',
            is_personal=True, verified=True),

    # Indonesia
    Account(name="", twitter_handler='jokowi',
            country_representing='ID', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='Menlu_Ri',
            country_representing='ID', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='DTDjani',
            country_representing='ID', role='',
            is_personal=True, verified=True),

    # Iran
    Account(name="", twitter_handler='hassanrouhani',
            country_representing='IR', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='jzarif',
            country_representing='IR', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='iran_un',
            country_representing='IR', role='',
            is_personal=False, verified=True),

    # Israel
    Account(name="", twitter_handler='netanyahu',
            country_representing='IL', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='IsraelMFA',
            country_representing='IL', role='',
            is_personal=False, verified=True),
    Account(name="", twitter_handler='IsraelinUN',
            country_representing='IL', role='',
            is_personal=False, verified=True),
    Account(name="", twitter_handler='IsraeliPM',
            country_representing='IL', role='',
            is_personal=False, verified=True),

    # Italy
    Account(name="Quirinale", twitter_handler='Quirinale',
            country_representing='IT', role='President',
            is_personal=False, verified=True),
    Account(name="Farnesina", twitter_handler='italymfa',
            country_representing='IT', role='',
            is_personal=False, verified=True),
    Account(name="Mariangela Zappia", twitter_handler='MAZappia',
            country_representing='IT', role='Ambassador and Permanent Representative to the United Nations ',
            is_personal=True, verified=False),

    # Japan
    Account(name="安倍晋三", twitter_handler='AbeShinzo',
            country_representing='JP', role='Prime Minister',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='MofaJapan_en',
            country_representing='JP', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='JapanMissionUN',
            country_representing='JP', role='',
            is_personal=True, verified=True),

    # Mexico
    Account(name="Andrés Manuel", twitter_handler='lopezobrador_',
            country_representing='MX', role='President',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='m_ebrard',
            country_representing='MX', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='JJGomezCamacho',
            country_representing='MX', role='',
            is_personal=True, verified=True),

    # Pakistan
    Account(name="Imran Khan", twitter_handler='ImranKhanPTI',
            country_representing='PK', role='Prime Minister',
            is_personal=True, verified=True),
    Account(name="Shah Mahmood Qureshi", twitter_handler='SMQureshiPTI',
            country_representing='PK', role='Foreign Minister',
            is_personal=True, verified=False),
    Account(name="Maleeha Lodhi", twitter_handler='LodhiMaleeha',
            country_representing='PK', role='Ambassador at the UN',
            is_personal=True, verified=False),
    Account(name="Pakistan Mission to the UN", twitter_handler='PakistanUN_NY',
            country_representing='PK', role='',
            is_personal=False, verified=False),

    # Russia
    Account(name="President of Russia", twitter_handler='KremlinRussia_E',
            country_representing='RU', role='',
            is_personal=False, verified=True),
    Account(name="MFA Russia", twitter_handler='mfa_russia',
            country_representing='RU', role='',
            is_personal=False, verified=True),
    Account(name="Russian Mission UN", twitter_handler='RussiaUN',
            country_representing='RU', role='',
            is_personal=False, verified=True),

    # Saudi Arabia
    Account(name="", twitter_handler='kingsalman',
            country_representing='SA', role='King',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='adelaljubeir',
            country_representing='SA', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='ksamissionun',
            country_representing='SA', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='ksamofaen',
            country_representing='SA', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='amouallimi',
            country_representing='SA', role='',
            is_personal=True, verified=True),

    # South Africa
    Account(name="", twitter_handler='CyrilRamaphosa',
            country_representing='ZA', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='LindiweSisuluSA',
            country_representing='ZA', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='SAMissionNY',
            country_representing='ZA', role='',
            is_personal=True, verified=True),

    # South Korea
    Account(name="", twitter_handler='TheBlueHouse_ENG',
            country_representing='KR', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='MOFAkr_ENG',
            country_representing='KR', role='',
            is_personal=True, verified=True),
    Account(name="", twitter_handler='ROK_UN',
            country_representing='KR', role='',
            is_personal=True, verified=True),

    # Turkey
    Account(name="Recep Tayyip Erdoğan", twitter_handler='RT_Erdogan',
            country_representing='TR', role='President',
            is_personal=True, verified=True),
    Account(name="Mevlüt Çavuşoğlu", twitter_handler='MevlutCavusoglu',
            country_representing='TR', role='Minister of Foreign Affairs',
            is_personal=True, verified=True),

    # United Kingdom
    Account(name="Theresa May", twitter_handler='theresa_may',
            country_representing='UK', role='',
            is_personal=True, verified=True),
    Account(name="Jeremy Hunt", twitter_handler='Jeremy_Hunt',
            country_representing='UK', role='Foreign Secretary',
            is_personal=True, verified=True),
    Account(name="Karen Pierce", twitter_handler='KarenPierceUN',
            country_representing='UK', role='Ambassador and Permanent Representative to the United Nations',
            is_personal=True, verified=True),

    # United Nations
    Account(name="United Nations", twitter_handler='',
            country_representing='UN', role='',
            is_personal=False, verified=True),
    Account(name="António Guterres", twitter_handler='antonioguterres',
            country_representing='UN', role='Secretary-General',
            is_personal=True, verified=True),

    # United States
    Account(name="Donald J. Trump", twitter_handler='realDonalfTrump',
            country_representing='US', role='President',
            is_personal=True, verified=True),
    Account(name="Secretary Pompeo", twitter_handler='SecPompeo',
            country_representing='US', role='Secretary of Department of State',
            is_personal=False, verified=True),
    Account(name="US Mission to the UN", twitter_handler='USUN',
            country_representing='US', role='',
            is_personal=False, verified=True),
    Account(name="President Trump", twitter_handler='POTUS',
            country_representing='US', role='President',
            is_personal=False, verified=True),

    # Others
    Account(name="Jamal Khashoggi", twitter_handler='JKhashoggi',
            country_representing=None, role='Journalist',
            is_personal=True, verified=True),
]
